// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	biz "backend/internal/biz"
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// GitCloneKafkaRepo is an autogenerated mock type for the GitCloneKafkaRepo type
type GitCloneKafkaRepo struct {
	mock.Mock
}

// CommitMessage provides a mock function with given fields: ctx, message
func (_m *GitCloneKafkaRepo) CommitMessage(ctx context.Context, message *kafka.Message) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMessage provides a mock function with given fields: ctx
func (_m *GitCloneKafkaRepo) GetMessage(ctx context.Context) (*kafka.Message, error) {
	ret := _m.Called(ctx)

	var r0 *kafka.Message
	if rf, ok := ret.Get(0).(func(context.Context) *kafka.Message); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishGitClone provides a mock function with given fields: ctx, gitClone
func (_m *GitCloneKafkaRepo) PublishGitClone(ctx context.Context, gitClone *biz.GitCloneEvent) error {
	ret := _m.Called(ctx, gitClone)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *biz.GitCloneEvent) error); ok {
		r0 = rf(ctx, gitClone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGitCloneKafkaRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewGitCloneKafkaRepo creates a new instance of GitCloneKafkaRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGitCloneKafkaRepo(t mockConstructorTestingTNewGitCloneKafkaRepo) *GitCloneKafkaRepo {
	mock := &GitCloneKafkaRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
