// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: scan/v1/scan.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScanClient is the client API for Scan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScanClient interface {
	ScanRepository(ctx context.Context, in *ScanRepositoryRequest, opts ...grpc.CallOption) (*ScanRepositoryResponse, error)
	GetScanRepositoryResult(ctx context.Context, in *GetScanRepositoryResultRequest, opts ...grpc.CallOption) (*GetScanRepositoryResultResponse, error)
}

type scanClient struct {
	cc grpc.ClientConnInterface
}

func NewScanClient(cc grpc.ClientConnInterface) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) ScanRepository(ctx context.Context, in *ScanRepositoryRequest, opts ...grpc.CallOption) (*ScanRepositoryResponse, error) {
	out := new(ScanRepositoryResponse)
	err := c.cc.Invoke(ctx, "/scan.v1.Scan/ScanRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) GetScanRepositoryResult(ctx context.Context, in *GetScanRepositoryResultRequest, opts ...grpc.CallOption) (*GetScanRepositoryResultResponse, error) {
	out := new(GetScanRepositoryResultResponse)
	err := c.cc.Invoke(ctx, "/scan.v1.Scan/GetScanRepositoryResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanServer is the server API for Scan service.
// All implementations must embed UnimplementedScanServer
// for forward compatibility
type ScanServer interface {
	ScanRepository(context.Context, *ScanRepositoryRequest) (*ScanRepositoryResponse, error)
	GetScanRepositoryResult(context.Context, *GetScanRepositoryResultRequest) (*GetScanRepositoryResultResponse, error)
	mustEmbedUnimplementedScanServer()
}

// UnimplementedScanServer must be embedded to have forward compatible implementations.
type UnimplementedScanServer struct {
}

func (UnimplementedScanServer) ScanRepository(context.Context, *ScanRepositoryRequest) (*ScanRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanRepository not implemented")
}
func (UnimplementedScanServer) GetScanRepositoryResult(context.Context, *GetScanRepositoryResultRequest) (*GetScanRepositoryResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScanRepositoryResult not implemented")
}
func (UnimplementedScanServer) mustEmbedUnimplementedScanServer() {}

// UnsafeScanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanServer will
// result in compilation errors.
type UnsafeScanServer interface {
	mustEmbedUnimplementedScanServer()
}

func RegisterScanServer(s grpc.ServiceRegistrar, srv ScanServer) {
	s.RegisterService(&Scan_ServiceDesc, srv)
}

func _Scan_ScanRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).ScanRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scan.v1.Scan/ScanRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).ScanRepository(ctx, req.(*ScanRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_GetScanRepositoryResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScanRepositoryResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).GetScanRepositoryResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scan.v1.Scan/GetScanRepositoryResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).GetScanRepositoryResult(ctx, req.(*GetScanRepositoryResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scan_ServiceDesc is the grpc.ServiceDesc for Scan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scan.v1.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanRepository",
			Handler:    _Scan_ScanRepository_Handler,
		},
		{
			MethodName: "GetScanRepositoryResult",
			Handler:    _Scan_GetScanRepositoryResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan/v1/scan.proto",
}
